@HitomiScrollViewerAPI_HostAddress = http://localhost:5155


GET {{HitomiScrollViewerAPI_HostAddress}}/debug/routes

###

GET {{HitomiScrollViewerAPI_HostAddress}}/api/gallery/2823006

###
    
GET {{HitomiScrollViewerAPI_HostAddress}}/api/tagfilter

###

GET {{HitomiScrollViewerAPI_HostAddress}}/api/tagfilter/3

###
