@HitomiScrollViewerAPI_HostAddress = http://localhost:5155

GET {{HitomiScrollViewerAPI_HostAddress}}/gallery/2823006
Accept: application/json

###
    
GET {{HitomiScrollViewerAPI_HostAddress}}/gallerycount
Accept: application/json

###
    